package sumcoda.boardbuddy.enumerate;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum District {

    // 서울
    SEOUL_ALL("전체"),
    SEOUL_GANGNAM("강남구"),
    SEOUL_GANGDONG("강동구"),
    SEOUL_GANGBUK("강북구"),
    SEOUL_GANGSEO("강서구"),
    SEOUL_GWANAK("관악구"),
    SEOUL_GWANGJIN("광진구"),
    SEOUL_GURO("구로구"),
    SEOUL_GEUMCHEON("금천구"),
    SEOUL_NOWON("노원구"),
    SEOUL_DOBONG("도봉구"),
    SEOUL_DONGDAEMUN("동대문구"),
    SEOUL_DONGJAK("동작구"),
    SEOUL_MAPO("마포구"),
    SEOUL_SEODAEMUN("서대문구"),
    SEOUL_SEOCHO("서초구"),
    SEOUL_SEONGDONG("성동구"),
    SEOUL_SEONGBUK("성북구"),
    SEOUL_SONGPA("송파구"),
    SEOUL_YANGCHEON("양천구"),
    SEOUL_YEONGDEUNGPO("영등포구"),
    SEOUL_YONGSAN("용산구"),
    SEOUL_EUNPYEONG("은평구"),
    SEOUL_JONGNO("종로구"),
    SEOUL_JUNG("중구"),
    SEOUL_JUNGRANG("중랑구"),

    // 경기
    GYEONGGI_ALL("전체"),
    GYEONGGI_GAPYEONG("가평군"),
    GYEONGGI_GOYANG_DEOKYANG("고양시 덕양구"),
    GYEONGGI_GOYANG_ILSANDONG("고양시 일산동구"),
    GYEONGGI_GOYANG_ILSANSEO("고양시 일산서구"),
    GYEONGGI_GWACHEON("과천시"),
    GYEONGGI_GWANGMYEONG("광명시"),
    GYEONGGI_GWANGJU("광주시"),
    GYEONGGI_GURI("구리시"),
    GYEONGGI_GUNPO("군포시"),
    GYEONGGI_GIMPO("김포시"),
    GYEONGGI_NAMYANGJU("남양주시"),
    GYEONGGI_DONGDUCHEON("동두천시"),
    GYEONGGI_BUCHEON("부천시"),
    GYEONGGI_SEONGNAM_BUNDANG("성남시 분당구"),
    GYEONGGI_SEONGNAM_SUJEONG("성남시 수정구"),
    GYEONGGI_SEONGNAM_JUNGWON("성남시 중원구"),
    GYEONGGI_SUWON_GWONSEON("수원시 권선구"),
    GYEONGGI_SUWON_YEONGTONG("수원시 영통구"),
    GYEONGGI_SUWON_JANGAN("수원시 장안구"),
    GYEONGGI_SUWON_PALDAL("수원시 팔달구"),
    GYEONGGI_SIHEUNG("시흥시"),
    GYEONGGI_ANSAN_DANWON("안산시 단원구"),
    GYEONGGI_ANSAN_SANGROK("안산시 상록구"),
    GYEONGGI_ANSEONG("안성시"),
    GYEONGGI_ANYANG_DONGAN("안양시 동안구"),
    GYEONGGI_ANYANG_MANAN("안양시 만안구"),
    GYEONGGI_YANGJU("양주시"),
    GYEONGGI_YANGPYEONG("양평군"),
    GYEONGGI_YEOJU("여주시"),
    GYEONGGI_YEONCHEON("연천군"),
    GYEONGGI_OSAN("오산시"),
    GYEONGGI_YONGIN_GIHEUNG("용인시 기흥구"),
    GYEONGGI_YONGIN_SUJI("용인시 수지구"),
    GYEONGGI_YONGIN_CHEOIN("용인시 처인구"),
    GYEONGGI_UIWANG("의왕시"),
    GYEONGGI_UIJEONGBU("의정부시"),
    GYEONGGI_ICHEON("이천시"),
    GYEONGGI_PAJU("파주시"),
    GYEONGGI_PYEONGTAEK("평택시"),
    GYEONGGI_POCHEON("포천시"),
    GYEONGGI_HANAM("하남시"),
    GYEONGGI_HWASEONG("화성시"),

    // 강원
    GANGWON_ALL("전체"),
    GANGWON_GANGNEUNG("강릉시"),
    GANGWON_GOSEONG("고성군"),
    GANGWON_DONGHAE("동해시"),
    GANGWON_SAMCHEOK("삼척시"),
    GANGWON_SOKCHO("속초시"),
    GANGWON_YANGGU("양구군"),
    GANGWON_YANGYANG("양양군"),
    GANGWON_YEONGWOL("영월군"),
    GANGWON_WONJU("원주시"),
    GANGWON_INJE("인제군"),
    GANGWON_JEONGSEON("정선군"),
    GANGWON_CHEORWON("철원군"),
    GANGWON_CHUNCHEON("춘천시"),
    GANGWON_TAEBAEK("태백시"),
    GANGWON_PYEONGCHANG("평창군"),
    GANGWON_HONGCHEON("홍천군"),
    GANGWON_HWACHEON("화천군"),
    GANGWON_HOENGSEONG("횡성군"),

    // 부산
    BUSAN_ALL("전체"),
    BUSAN_GANGSEO("강서구"),
    BUSAN_GEUMJEONG("금정구"),
    BUSAN_GIJANG("기장군"),
    BUSAN_NAMGU("남구"),
    BUSAN_DONGGU("동구"),
    BUSAN_DONGRAE("동래구"),
    BUSAN_BUSANJIN("부산진구"),
    BUSAN_BUKGU("북구"),
    BUSAN_SASANG("사상구"),
    BUSAN_SAHA("사하구"),
    BUSAN_SEOGU("서구"),
    BUSAN_SUYONG("수영구"),
    BUSAN_YEONJE("연제구"),
    BUSAN_YEONGDO("영도구"),
    BUSAN_JUNG("중구"),
    BUSAN_HAEUNDAE("해운대구"),

    // 대구
    DAEGU_ALL("전체"),
    DAEGU_NAMGU("남구"),
    DAEGU_DALSEO("달서구"),
    DAEGU_DALSEONG("달성군"),
    DAEGU_DONGGU("동구"),
    DAEGU_BUKGU("북구"),
    DAEGU_SEOGU("서구"),
    DAEGU_SUSEONG("수성구"),
    DAEGU_JUNG("중구"),

    // 인천
    INCHEON_ALL("전체"),
    INCHEON_GANGHWA("강화군"),
    INCHEON_GYEYANG("계양구"),
    INCHEON_MICHUHOL("미추홀구"),
    INCHEON_NAMDONG("남동구"),
    INCHEON_DONGGU("동구"),
    INCHEON_BUPYEONG("부평구"),
    INCHEON_SEOGU("서구"),
    INCHEON_YEONSU("연수구"),
    INCHEON_ONGJIN("옹진군"),
    INCHEON_JUNG("중구"),

    // 광주
    GWANGJU_ALL("전체"),
    GWANGJU_GWANGSAN("광산구"),
    GWANGJU_NAMGU("남구"),
    GWANGJU_DONGGU("동구"),
    GWANGJU_BUKGU("북구"),
    GWANGJU_SEOGU("서구"),

    // 대전
    DAEJEON_ALL("전체"),
    DAEJEON_DADEOK("대덕구"),
    DAEJEON_DONGGU("동구"),
    DAEJEON_SEOGU("서구"),
    DAEJEON_YUSEONG("유성구"),
    DAEJEON_JUNG("중구"),

    // 울산
    ULSAN_ALL("전체"),
    ULSAN_NAMGU("남구"),
    ULSAN_DONGGU("동구"),
    ULSAN_BUKGU("북구"),
    ULSAN_ULJUGUN("울주군"),
    ULSAN_JUNG("중구"),

    // 세종
    SEJONG_ALL("전체"),

    // 충북
    CHUNGBUK_ALL("전체"),
    CHUNGBUK_GOESAN("괴산군"),
    CHUNGBUK_DANYANG("단양군"),
    CHUNGBUK_BOEUN("보은군"),
    CHUNGBUK_YEONGDONG("영동군"),
    CHUNGBUK_OKCHEON("옥천군"),
    CHUNGBUK_EUMSEONG("음성군"),
    CHUNGBUK_JECHEON("제천시"),
    CHUNGBUK_JEUNGPYEONG("증평군"),
    CHUNGBUK_JINCHEON("진천군"),
    CHUNGBUK_CHEONGJU_SANGDANG("청주시 상당구"),
    CHUNGBUK_CHEONGJU_SEOWON("청주시 서원구"),
    CHUNGBUK_CHEONGJU_CHEONGWON("청주시 청원구"),
    CHUNGBUK_CHEONGJU_HEUNGDEOK("청주시 흥덕구"),
    CHUNGBUK_CHUNGJU("충주시"),

    // 충남
    CHUNGNAM_ALL("전체"),
    CHUNGNAM_GYERYONG("계룡시"),
    CHUNGNAM_GONGJU("공주시"),
    CHUNGNAM_GEUMSAN("금산군"),
    CHUNGNAM_NONSAN("논산시"),
    CHUNGNAM_DANGJIN("당진시"),
    CHUNGNAM_BORYEONG("보령시"),
    CHUNGNAM_BUYEO("부여군"),
    CHUNGNAM_SEOSAN("서산시"),
    CHUNGNAM_SEOCHEON("서천군"),
    CHUNGNAM_ASAN("아산시"),
    CHUNGNAM_YESAN("예산군"),
    CHUNGNAM_CHEONAN_DONGNAM("천안시 동남구"),
    CHUNGNAM_CHEONAN_SEOBUK("천안시 서북구"),
    CHUNGNAM_CHEONGYANG("청양군"),
    CHUNGNAM_TAEAN("태안군"),
    CHUNGNAM_HONGSEONG("홍성군"),

    // 전북
    JEONBUK_ALL("전체"),
    JEONBUK_GOCHANG("고창군"),
    JEONBUK_GUNSAN("군산시"),
    JEONBUK_GIMJE("김제시"),
    JEONBUK_NAMWON("남원시"),
    JEONBUK_MUJU("무주군"),
    JEONBUK_BUAN("부안군"),
    JEONBUK_SUNCHANG("순창군"),
    JEONBUK_WANJU("완주군"),
    JEONBUK_IKSAN("익산시"),
    JEONBUK_IMSIL("임실군"),
    JEONBUK_JANGSU("장수군"),
    JEONBUK_JEONJU_DEOKJIN("전주시 덕진구"),
    JEONBUK_JEONJU_WANSAN("전주시 완산구"),
    JEONBUK_JEONGEUP("정읍시"),
    JEONBUK_JINAN("진안군"),

    // 전남
    JEONNAM_ALL("전체"),
    JEONNAM_GANGJIN("강진군"),
    JEONNAM_GOHEUNG("고흥군"),
    JEONNAM_GOKSEONG("곡성군"),
    JEONNAM_GWANGYANG("광양시"),
    JEONNAM_GURAE("구례군"),
    JEONNAM_NAJU("나주시"),
    JEONNAM_DAMYANG("담양군"),
    JEONNAM_MOKPO("목포시"),
    JEONNAM_MUAN("무안군"),
    JEONNAM_BOSEONG("보성군"),
    JEONNAM_SUNCHEON("순천시"),
    JEONNAM_SINAN("신안군"),
    JEONNAM_YEOSU("여수시"),
    JEONNAM_YEONGGWANG("영광군"),
    JEONNAM_YEONGAM("영암군"),
    JEONNAM_WANDO("완도군"),
    JEONNAM_JANGSEONG("장성군"),
    JEONNAM_JANGHEUNG("장흥군"),
    JEONNAM_JINDO("진도군"),
    JEONNAM_HAMPYEONG("함평군"),
    JEONNAM_HAENAM("해남군"),
    JEONNAM_HWASUN("화순군"),

    // 경북
    GYEONGBUK_ALL("전체"),
    GYEONGBUK_GYEONGSAN("경산시"),
    GYEONGBUK_GYEONGJU("경주시"),
    GYEONGBUK_GORYEONG("고령군"),
    GYEONGBUK_GUMI("구미시"),
    GYEONGBUK_GUNWI("군위군"),
    GYEONGBUK_KIMCHEON("김천시"),
    GYEONGBUK_MUNGYEONG("문경시"),
    GYEONGBUK_BONGHWA("봉화군"),
    GYEONGBUK_SANGJU("상주시"),
    GYEONGBUK_SEONGJU("성주군"),
    GYEONGBUK_ANDONG("안동시"),
    GYEONGBUK_YEONGDEOK("영덕군"),
    GYEONGBUK_YEONGYANG("영양군"),
    GYEONGBUK_YEONGJU("영주시"),
    GYEONGBUK_YEONGCHEON("영천시"),
    GYEONGBUK_YECHEON("예천군"),
    GYEONGBUK_ULLEUNG("울릉군"),
    GYEONGBUK_ULJIN("울진군"),
    GYEONGBUK_UISEONG("의성군"),
    GYEONGBUK_CHEONGDO("청도군"),
    GYEONGBUK_CHEONGSONG("청송군"),
    GYEONGBUK_CHILGOK("칠곡군"),
    GYEONGBUK_POHANG_NAMGU("포항시 남구"),
    GYEONGBUK_POHANG_BUKGU("포항시 북구"),

    // 경남
    GYEONGNAM_ALL("전체"),
    GYEONGNAM_GEOJE("거제시"),
    GYEONGNAM_GEACHANG("거창군"),
    GYEONGNAM_GOSEONG("고성군"),
    GYEONGNAM_GIMHAE("김해시"),
    GYEONGNAM_NAMHAE("남해군"),
    GYEONGNAM_MIRYANG("밀양시"),
    GYEONGNAM_SACHEON("사천시"),
    GYEONGNAM_SANCHEONG("산청군"),
    GYEONGNAM_YANGSAN("양산시"),
    GYEONGNAM_UIRYEONG("의령군"),
    GYEONGNAM_JINJU("진주시"),
    GYEONGNAM_CHANGNYEONG("창녕군"),
    GYEONGNAM_CHANGWON_MASANHAPPO("창원시 마산합포구"),
    GYEONGNAM_CHANGWON_MASANHOE("창원시 마산회원구"),
    GYEONGNAM_CHANGWON_SEONGSAN("창원시 성산구"),
    GYEONGNAM_CHANGWON_UICHANG("창원시 의창구"),
    GYEONGNAM_CHANGWON_JINHAE("창원시 진해구"),
    GYEONGNAM_TONGYEONG("통영시"),
    GYEONGNAM_HADONG("하동군"),
    GYEONGNAM_HAMAN("함안군"),
    GYEONGNAM_HAMYANG("함양군"),
    GYEONGNAM_HAPCHEON("합천군"),

    // 제주
    JEJU_ALL("전체"),
    JEJU_SEOGWIPO("서귀포시"),
    JEJU_JEJU("제주시");

    private final String name;
}
